### ISSUE TITLE
How to customize video record layout  ?

### ISSUE THREAD

**Issue by rameshkec85** [Ziggeo/Android-Client-SDK#9]
First I would like to thank for wonderful sdk. 
      I am facing the issue on customization for embedded video recorder. voice, camera switch, done, start recording options should be out side of the video view (will use custom buttons as per my design). I do not want show any icon in the video view.

can you please help me on this ?

1. OnPageLoad recording should be started through front cam
2. Camera switch access
3. By Tapping Stop button, video recording should be stop and start upload to server 

![screenshot from 2016-12-03 20-20-40](https://cloud.githubusercontent.com/assets/1030165/20860092/25791618-b996-11e6-9d4b-495bde91e300.png)

**Comment by 3akat** [comment]
Hi @rameshkec85,
You can change default camera to front by putting `Camera.CameraInfo.CAMERA_FACING_FRONT` as argument for `preferredCameraId`.
Unfortunately there is no way for ui customisation for now. On monday I will think what will be the best way for such kind of functionality and will back to you with estimates for it.

**Comment by rameshkec85** [comment]
@3akat  Thanks very much. Can you fix it asap as this is urgent requirement for me.

**Comment by 3akat** [comment]
@rameshkec85 
Already working on it, will be ready tomorrow.

**Comment by 3akat** [comment]
Hi @rameshkec85,
I've added ability to specify custom layout for recorder. To do it you will need
1. Update to latest sdk version.
2. Use method `.setRecorderLayout(int layoutResId)`
3. In your custom layout if you need everything from default layout but with custom designs you need to use following ids for your views:
* vg_recorder - for root view
* sv_video - for SurfaceView
* iv_voice_indicator - for sound indicator
* tv_time_status - for recording time progress
* v_play - for starting video player
* v_switch_camera - for camera switching
* v_start_stop - for start and stop recording
* v_send_and_close - for ability to send video immidiate

If you need only views which are shown in you screenshot, you will need
* sv_video - for SurfaceView
* tv_time_status - for recording time progress
* v_start_stop - for start and stop recording.

Feel free to tell me if you need something more.

**Comment by rameshkec85** [comment]
Button clicks are not working. Can you try with the following code in your sample(by update the latest version) and I want to remove select thumbnail after stop the video reocrding (it should not be displayed  since user should not interact with recording.).


**my_custom.xml**

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
   >


    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="5dp"
        android:background="#FD0"
        android:gravity="center_vertical">

        <ImageView
            android:id="@id/iv_switch_camera"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="5dp"
            android:src="@drawable/ic_switch_camera"
            android:text="@string/start" />

        <ImageView
            android:id="@id/iv_start"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="5dp"
            android:src="@drawable/ic_start"
            android:text="@string/start" />

        <ImageView
            android:id="@id/iv_play"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_play"
            android:text="@string/start" />

    </LinearLayout>


    <com.ziggeo.androidsdk.ui.views.AdaptiveSurfaceView
        android:id="@id/sv_video"
        android:layout_width="200dp"
        android:layout_height="200dp"
        android:layout_gravity="center_horizontal" />


</LinearLayout>


Activity: 
        setContentView(R.layout.activity_main);
        Ziggeo ziggeo = new Ziggeo(APP_TOKEN);
        long maxDuration = 20000L;
        ziggeo.setSendImmediately(false);
        ziggeo.setRecorderLayout(R.layout.my_custom);
        ziggeo.attachRecorder(getFragmentManager(), R.id.fl_content, maxDuration, true, this);

**Comment by 3akat** [comment]
@rameshkec85 
From what I can see, you're not following rules that I've described above.
1. You don't need `ziggeo.setSendImmediately(false);`
2. ids should be 
- `v_switch_camera` instead of `iv_switch_camera`
- `v_start_stop` instead of `iv_start`
- `v_play` instead of `iv_play`

Regarding to other points.
If seems you've missed some part of your layout, when you will provide full layout I will test it.
Also hiding thumbnail selection is not currently supported. Will start work now on it.

`com.ziggeo.androidsdk.ui.views.AdaptiveSurfaceView` is not prepared to fit any random size, it needs to be improved, I will do it, but it will take some time, so if you need it asap you can make your own implementation.

**Comment by rameshkec85** [comment]
@3akat Thanks very much. Its working now except thumbnail selection and customizing surface view (I'll try to customize it).

**Comment by 3akat** [comment]
Hi @rameshkec85,
I've updated sdk, please use `ziggeo.setShowCoverShotSelectionPopup(false)` to prevent thumbnail selection.

**Comment by rameshkec85** [comment]
Thanks very much @3akat 

Its not picking up the custom layout if using the following code.

```
        ziggeo.setRecorderLayout(R.layout.my_custom);
        ziggeo.attachRecorder(getFragmentManager(), R.id.fl_content, maxDuration, Camera.CameraInfo.CAMERA_FACING_FRONT, this);

```

where this is working fine with custom layout but I want to force camera front face .
```
        ziggeo.setRecorderLayout(R.layout.my_custom);
        ziggeo.attachRecorder(getFragmentManager(), R.id.fl_content, maxDuration, false, this);

```
And I have one more doubt, how to start auto start recording without tapping button ?

   ```
  Ziggeo ziggeo = new Ziggeo(APP_TOKEN, this);
        long maxDuration = 20000L;
        ziggeo.setSendImmediately(true);
        ziggeo.setShowCoverShotSelectionPopup(false);
        ziggeo.setRecorderLayout(R.layout.my_custom);
        ziggeo.attachRecorder(getFragmentManager(), R.id.fl_content, maxDuration, false, this);
   
```

**Comment by 3akat** [comment]
Hi @rameshkec85,
Will check the bugs today.
Unfortunately there is no ability to start recording without tapping button. Are you sure you need it? It seems user need some time to focus camera on things he want to shoot.

**Comment by rameshkec85** [comment]
@3akat  Yes, this is major requirement for my app (start recording on load) or else  Can you give callback once camera is ready ?

**Comment by 3akat** [comment]
@rameshkec85 I can start recording right after screen loads, but the camera need some time to start recording. On some devices it will take 0.5 second, on some maybe 2 seconds. How in that case we should indicate that recording was started?

**Comment by 3akat** [comment]
@rameshkec85 
Fixed bugs with cover shot popup and custom layout.

**Comment by 3akat** [comment]
Closing it due to inactivity.
@rameshkec85 please, open it if you have any issues regarding recorder customization.

**Comment by rameshkec85** [comment]
Hi,
I am still facing many customisation issues using this sdk. Can u help me on this ? or can u provide  control on VideoRecorderFragment ? 

- I want to play the recording video. (there is no way to get recorded file name)
- Needs to add Begin, Stop && finish etc. based on the recording state. 
- Timer format needs to be changed as per my requirement (ex. 5 Secs )

I felt very difficult to customising UI based on my requirement. Is there any work around this ?

**Comment by 3akat** [comment]
Hi @rameshkec85,
The things you described related more to functionality than to UI castomisation. 
> Needs to add Begin, Stop && finish etc. based on the recording state.

Such functionality requires a lot of architectural changes, so it will not be ready in nearest time. 

> I want to play the recording video. (there is no way to get recorded file name)

There is method in ziggeo class called `setVideoRecordingProcessCallback`, I will update callback and put path there. 

> Timer format needs to be changed as per my requirement (ex. 5 Secs )

I can add ability to set custom formatter for time in millis. Will it be enough?

**Comment by rameshkec85** [comment]
@3akat : 
Thanks,
1. Provide me the url that i can play it ziggeo video player in one screen (should be embeded in screen where other buttons also required to place)
2. Custom Timer format

**Comment by 3akat** [comment]
Hi @rameshkec85,
We've added `CameraView` in new version. 
Please, check it out, it provides ability for any customisations.
